---
driver:
  name: docker
  # https://github.com/test-kitchen/kitchen-docker/issues/207#issuecomment-218544624
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: instances
  additional_copy_path:
    # for some reason this isn't copied by default
    - test/integration/default/files

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
